//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTypeApp.ManufactureService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.web.courses.org/", ConfigurationName="ManufactureService.ManufactureService")]
    public interface ManufactureService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestTypeApp.ManufactureService.DeactivateResponse Deactivate(TestTypeApp.ManufactureService.Deactivate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureService.DeactivateResponse> DeactivateAsync(TestTypeApp.ManufactureService.Deactivate request);
        
        // CODEGEN: Parameter '_return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_return")]
        TestTypeApp.ManufactureService.SaveResponse Save(TestTypeApp.ManufactureService.Save request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureService.SaveResponse> SaveAsync(TestTypeApp.ManufactureService.Save request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.ManufactureService.ReadAllResponse ReadAll(TestTypeApp.ManufactureService.ReadAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureService.ReadAllResponse> ReadAllAsync(TestTypeApp.ManufactureService.ReadAll request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Deactivate", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class Deactivate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] arg0;
        
        public Deactivate() {
        }
        
        public Deactivate(int[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class DeactivateResponse {
        
        public DeactivateResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.web.courses.org/")]
    public partial class manufacture : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activeField;
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.web.courses.org/")]
    public partial class SaveResponseEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("valueSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class Save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.ManufactureService.manufacture[] arg0;
        
        public Save() {
        }
        
        public Save(TestTypeApp.ManufactureService.manufacture[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class SaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TestTypeApp.ManufactureService.SaveResponseEntry[] _return;
        
        public SaveResponse() {
        }
        
        public SaveResponse(TestTypeApp.ManufactureService.SaveResponseEntry[] _return) {
            this._return = _return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAll", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class ReadAll {
        
        public ReadAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class ReadAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.ManufactureService.manufacture[] @return;
        
        public ReadAllResponse() {
        }
        
        public ReadAllResponse(TestTypeApp.ManufactureService.manufacture[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManufactureServiceChannel : TestTypeApp.ManufactureService.ManufactureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManufactureServiceClient : System.ServiceModel.ClientBase<TestTypeApp.ManufactureService.ManufactureService>, TestTypeApp.ManufactureService.ManufactureService {
        
        public ManufactureServiceClient() {
        }
        
        public ManufactureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManufactureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufactureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufactureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.ManufactureService.DeactivateResponse TestTypeApp.ManufactureService.ManufactureService.Deactivate(TestTypeApp.ManufactureService.Deactivate request) {
            return base.Channel.Deactivate(request);
        }
        
        public void Deactivate(int[] arg0) {
            TestTypeApp.ManufactureService.Deactivate inValue = new TestTypeApp.ManufactureService.Deactivate();
            inValue.arg0 = arg0;
            TestTypeApp.ManufactureService.DeactivateResponse retVal = ((TestTypeApp.ManufactureService.ManufactureService)(this)).Deactivate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureService.DeactivateResponse> TestTypeApp.ManufactureService.ManufactureService.DeactivateAsync(TestTypeApp.ManufactureService.Deactivate request) {
            return base.Channel.DeactivateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.ManufactureService.DeactivateResponse> DeactivateAsync(int[] arg0) {
            TestTypeApp.ManufactureService.Deactivate inValue = new TestTypeApp.ManufactureService.Deactivate();
            inValue.arg0 = arg0;
            return ((TestTypeApp.ManufactureService.ManufactureService)(this)).DeactivateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.ManufactureService.SaveResponse TestTypeApp.ManufactureService.ManufactureService.Save(TestTypeApp.ManufactureService.Save request) {
            return base.Channel.Save(request);
        }
        
        public TestTypeApp.ManufactureService.SaveResponseEntry[] Save(TestTypeApp.ManufactureService.manufacture[] arg0) {
            TestTypeApp.ManufactureService.Save inValue = new TestTypeApp.ManufactureService.Save();
            inValue.arg0 = arg0;
            TestTypeApp.ManufactureService.SaveResponse retVal = ((TestTypeApp.ManufactureService.ManufactureService)(this)).Save(inValue);
            return retVal._return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureService.SaveResponse> TestTypeApp.ManufactureService.ManufactureService.SaveAsync(TestTypeApp.ManufactureService.Save request) {
            return base.Channel.SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.ManufactureService.SaveResponse> SaveAsync(TestTypeApp.ManufactureService.manufacture[] arg0) {
            TestTypeApp.ManufactureService.Save inValue = new TestTypeApp.ManufactureService.Save();
            inValue.arg0 = arg0;
            return ((TestTypeApp.ManufactureService.ManufactureService)(this)).SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.ManufactureService.ReadAllResponse TestTypeApp.ManufactureService.ManufactureService.ReadAll(TestTypeApp.ManufactureService.ReadAll request) {
            return base.Channel.ReadAll(request);
        }
        
        public TestTypeApp.ManufactureService.manufacture[] ReadAll() {
            TestTypeApp.ManufactureService.ReadAll inValue = new TestTypeApp.ManufactureService.ReadAll();
            TestTypeApp.ManufactureService.ReadAllResponse retVal = ((TestTypeApp.ManufactureService.ManufactureService)(this)).ReadAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureService.ReadAllResponse> TestTypeApp.ManufactureService.ManufactureService.ReadAllAsync(TestTypeApp.ManufactureService.ReadAll request) {
            return base.Channel.ReadAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.ManufactureService.ReadAllResponse> ReadAllAsync() {
            TestTypeApp.ManufactureService.ReadAll inValue = new TestTypeApp.ManufactureService.ReadAll();
            return ((TestTypeApp.ManufactureService.ManufactureService)(this)).ReadAllAsync(inValue);
        }
    }
}
